# Generated by Django 2.2.6 on 2019-10-12 13:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('testparcer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parceline',
            name='dtimefield',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
